- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest


- name: Place Nginx config for uWSGI
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: 
    - Restart Nginx Service
    - Stop systemd-resolved
    - Place resolv.conf 

- name: Ensure Nginx is started
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started
