- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: Place Nginx config
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: 
    - Restart Nginx service

- name: Ensure Nginx is started
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started
