- name: Create Grafana directories
  ansible.builtin.file:
    path: "/opt/grafana/provisioning/{{ item }}"
    state: directory
    recurse: yes
  loop:
     - dashboards
     - datasources

- name: Place grafana configuration
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
    mode: '0744'
    force: yes
  notify: Restart Grafana container
  no_log: true
  
- name: Place Grafana dashboards
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/grafana/provisioning/dashboards/{{ item }}"
    mode: '0744'
  loop:
     - main.json
     - mysql.json
     - syslog.json
     - pdashboard.yaml
  notify: Restart Grafana container
  
- name: Place Grafana datasources
  ansible.builtin.template:
    src: prometheus.yaml.j2
    dest: /opt/grafana/provisioning/datasources/prometheus.yaml
    force: yes
    mode: '0744'    
  notify: Restart Grafana container

- name: Grafana Docker container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:8.3.3
    volumes: /opt/grafana:/etc/grafana
    restart_policy: always
    published_ports: "{{ grafana_port }}:3000"
    container_default_behavior: no_defaults