
- name: Install nessesary package for grafana
  apt: 
      name: apt-transport-https
      state: present
      update_cache: yes
  notify: 
    - Add grafana gpg key
    - Add grafana repo
    - Install grafana
    - Add grafana password
    - Enable and start grafana service
    - Place grafana configuration
    - Place prometheus datasource
    - Place prometheus dashboard
    - Place main.json
    - Restart grafana service
    - Restart prometheus-mysqld-exporter
    - Restart mysql service
    - Restart bind9 service


