
- name: Install nessesary package for grafana
  apt: 
      name: apt-transport-https
      state: present
  notify: 
    - Add grafana gpg key
    - Add grafana repo
    - Install grafana
    - Add grafana password
    - Enable and start grafana service
    - Place grafana configuration
    - Place prometheus datasource
    - Place prometheus dashboard
    - Place main.json
    - Place syslog.json 
    - Restart grafana service
    # - Restart prometheus-mysqld-exporter
    # - Restart mysql service
    # - Restart bind9 service
    - Give permissions to grafana.log
    - Give permissions to grafana.db
