- name: Install uWSGI packages
  ansible.builtin.apt:
    name: 
      - uwsgi
      - uwsgi-plugin-python3
    state: latest
    

- name: Place uWSGI configuration
  ansible.builtin.template:
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify: Restart uWSGI service

- name: Ensure uWSGI is started
  ansible.builtin.service:
    name: uwsgi
    enabled: yes
    state: started
