{
 "title": "Main Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Keepalived VRRP state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state", "legendFormat": "{{instance}}" },
    {}
   ]
  },
  {
   "title": "Haproxy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Nginx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Keepalived ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Nginx requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 4 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Haproxy server status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "haproxy_server_up", "legendFormat": "{{instance}}: {{server}}" },
    {}
   ]
  },
  {
   "title": "Bind9",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": " DNS queries/minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 15 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total[1m])",
     "legendFormat": "{{instance}}; {{type}}"
    }
   ]
  },
  {
   "title": "InfluxDB write rate ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "targets": [
    { "expr": "influxdb_write_write_ok", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Influx Health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "[[tag_dst]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dst" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "MySQL selects/minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total[1m])",
     "legendFormat": "{{instance}}; {{command}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total[1m])",
     "legendFormat": "{{instance}}; {{mode}}"
    }
   ]
  }
 ]
}