- name: Create Agama /opt/agama
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    recurse: yes

- name: Download Ansible Dockerfile
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile

- name: Build Agama docker image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama
    
- name: Agama Docker containers:"{{ agama_instances }}" 
  community.docker.docker_container:
    name: "agama{{ item }}"
    image: agama
    published_ports: "{{ agama_port + item | int }}:8000"
    container_default_behavior: no_defaults
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{mysql_user}}:{{mysql_password}}@{{mysql_host}}/{{mysql_database}}
  with_sequence: count={{ agama_instances }}

# - name: Restart agama container
#   docker_container:
#     name: agama
#     image: agama
#     restart: yes
#     container_default_behavior: no_defaults
#     env:
#       AGAMA_DATABASE_URI: mysql+pymysql://{{mysql_user}}:{{mysql_password}}@{{mysql_host}}/{{mysql_database}}

- name: Start Agama containers:"{{ agama_instances }}" 
  docker_container:
    name: "agama{{ item }}"
    image: agama
    state: started
    container_default_behavior: no_defaults
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{mysql_user}}:{{mysql_password}}@{{mysql_host}}/{{mysql_database}}
  with_sequence: count={{ agama_instances }}