- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart Prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: Restart node_exporters
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: restarted