- name: Set CNAME records
  community.general.nsupdate:
    key_name: "dns_update_key"
    key_secret: "{{ dns_update_key }}"
    key_algorithm: "hmac-sha256"
    server: "localhost"
    zone: "{{ startup_name }}"
    record: "{{ item.key }}"
    type: "CNAME"
    value: "{{ item.value }}"
  loop: "{{ dns_cname_records | dict2items }}"
  run_once: true