- name: Create /home/backup/influxdb
  ansible.builtin.file:
    path: /home/backup/influxdb
    state: directory
    owner: backup
    mode: '0744'

- name: Create /etc/cron.d/influxdb-backup 
  ansible.builtin.template:
    src: influxdb-backup.j2 
    dest: /etc/cron.d/influxdb-backup 
    force: yes
    mode: '0744'
