---
# - name: TEST
#   template:
#     dest: /zeta
#     src: zeta.j2

- name: Place "{{ db_name }}"
  ansible.builtin.lineinfile:
    path: /zeta
    regexp: '; Serial'
    line: '                {{ dns_serial }}      	; Serial'
  when: inventory_hostname in groups['dns_master']