- name: Restart Nginx Service
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Stop systemd-resolved
  shell: sudo systemctl stop systemd-resolved

- name: Place resolv.conf 
  ansible.builtin.template:
    src: resolv.conf
    dest: /etc/resolv.conf
    force: yes