{
 "title": "MySQL Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "MySQL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "MySQL selects/minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total[1m])"
    }
   ]
  },
  {
   "title": "MySQL replication threads ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running"
    },
    {
     "expr": "mysql_slave_status_slave_sql_running"
    }
   ]
  },
  {
   "title": "MySQL server ID's",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id"
    }
   ]
  },
  {
   "title": "MySQL server read only status ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only"
    }
   ]
  }
 ]
}