- name: Add user pinger
  ansible.builtin.user:
    name: pinger

- name: Install  fping
  ansible.builtin.apt:
    name: fping
    state: latest

- name: Place pinger.service 
  ansible.builtin.template:
    src: pinger.service
    dest: /etc/systemd/system/
    force: yes
    owner: pinger
    group: pinger
    mode: '0764'
  notify: 
    - Reload daemon
    - Start pinger

- name: Place pinger.sh script
  ansible.builtin.template:
    src: pinger.sh
    dest: /usr/local/bin/pinger
    force: yes
    owner: pinger
    group: pinger
    mode: '0764'
  notify: 
    - Reload daemon
    - Restart pinger

- name: Create a directory /etc/pinger/
  ansible.builtin.file:
    path: /etc/pinger
    state: directory
    owner: pinger
    group: pinger
    mode: '0764'

- name: Place pinger.conf 
  ansible.builtin.template:
    src: pinger.conf.j2
    dest: /etc/pinger/pinger.conf
    force: yes
    mode: '0764'
  notify: 
    - Reload daemon
    - Restart pinger

- name: Pinger is started
  ansible.builtin.service:
    name: pinger
    enabled: yes
    state: started

