- name: Start influxdb service
  ansible.builtin.service:
    name: influxdb
    state: started

- name: Restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted

- name: Restart influxdb
  ansible.builtin.service:
    name: influxdb
    state: restarted


