- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart node_exporters
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: restarted

- name: Ensure nginx-exporter is started
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    enabled: yes
    state: restarted