- name: Install Docker package
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-docker
  register: docker_install

- name: add user to docker group
  user:
    name: ubuntu
    group: docker

- name: iptables-persistent 
  apt:
    name: iptables-persistent 

- name: iptables-save -t mangle
  shell: iptables-save -t mangle
  when: docker_install.changed

- name: /var/local/iptables.mangle
  template:
    src: iptables.mangle
    dest: /var/local/iptables.mangle
  when: docker_install.changed

- name: Perform iptables-restore
  community.general.iptables_state:
    path: /var/local/iptables.mangle
    state: restored
    table: mangle
  when: docker_install.changed

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Log into DockerHub
  docker_login:
    username: sekapictures
    password: "{{ docker_password }}"
    email: sekapictures@gmail.com
  no_log: true

# - name: Change /var/run/docker.sock permissions
#   ansible.builtin.file:
#     path: /var/run/docker.sock
#     mode: '0666'
